- CHANGELOG.md
- Gemfile.lock
- lib/active_stash/relation.rb
- lib/active_stash/search.rb
- spec/query_spec.rb
- spec/search_spec.rb
* Fixed an issue where calling `joins` or `includes` before (or after) `query` fails
* Ensure that `stash_id` is set if `cs_put` is called outside of a callback
* Don't call `save` when bulk reindexing to avoid updating timestamps unnecessarily
> Fixes and improvements

- README.md
- bin/setup
This PR cleans up a few minor details in README.md and bin/setup.
README.md changes:
* Add missing backticks in  index types tables
* Escape pipes in range query example to fix table formatting
* Remove generic text generated by `bundle gem`
bin/setup:
* Remove comment that gets printed to stdout
> Readme and setup cleanup

- README.md
- lib/active_stash/query_builder.rb
- lib/active_stash/relation.rb
- spec/query_spec.rb
This PR implements the `between` operator in range queries.
`between` takes two separate `min` and `max` args for consistency with the implementation in StashRB, but I'm open to other ideas (e.g. if we think a range would be cleaner).
> Implement between operator in range queries

- .tool-versions
- README.md
The intent of this change is to document just enough to cover
Healthbank's needs until Matt's zero-downtime migrations epic is
complete. This should get our customer over the hump.
Matt's documentation PR https://github.com/cipherstash/platform/pull/954
will override this once his work is merged.
> Documentation: re-indexing

- README.md
- activestash.gemspec
- lib/active_stash.rb
- lib/active_stash/collection_proxy.rb
- lib/active_stash/railtie.rb
This change implements configuration via Rails config (e.g. in
environment-specific config, application.rb, an initializer, etc.)
as well as Rails credentials files.
> Allow client config via Rails config and credentials

- lib/active_stash/collection_proxy.rb
This will avoid an authentication roundtrip which may hurt performance.
> Cache @client connection in CollectionProxy

- spec/put_spec.rb
- spec/query_spec.rb
1. Ensure the specs have unique group names as this affects when
before(:context) and after(:context) runs and avoids races with
create and deleting collections
2. Explicitly delete data created in the specs before and after tests.
> Fix spec race conditions

- spec/active_stash/consistency_spec.rb
I'm unsure what the semantics are of before/after with no-arg (just a
block) so I'm being explicit.
> DRY up before/after blocks in consistency spec

- README.md
This fixes broken formatting in the markdown table.
> Escape pipes in "String and Text" query example in README

- activestash.gemspec
Removing funding_uri since we decided that it's more annoying than actually helpful.
> Remove funding_uri from gem metadata

- activestash.gemspec
ActiveStash has a dependancy on Rails in dev because it's needed in order to run the test suite that depends on Railties.
When adding ActiveStash and running through the getting started guide locally on a rails app, I was getting these warning messages
```
/Users/fionamccawley/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/fionamccawley/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/fionamccawley/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
```
https://github.com/ruby/net-protocol/issues/10
Adding `net-http` to the gem …
> Add net-http as a dev dependancy

- activestash.gemspec
- lib/tasks/active_stash.rake
Ticket https://www.notion.so/cipherstash/Rake-task-to-sign-up-to-CipherStash-c5acb5ae50024808ad405fb8faabcff4
This console PR will be merged first. https://github.com/cipherstash/console/pull/70
I couldn't work out how to auto login back in the terminal after the sign up flow. So the above console PR displays the next step for the user to head back to the terminal and use the rake task to login.
> Add rake task to launch signup

- .github/workflows/build.yml
Otherwise everything goes pear-shaped if you attempt to re-run
a workflow, because nothing cleans up properly after itself.
> Include the run attempt in the collection name

- .github/workflows/build.yml
- activestash.gemspec
When running any rails command on a Rails App (v7) Ruby (2.7.4) with ActiveStash installed, these warning messages output.
```
/Users/fionamccawley/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/fionamccawley/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/fionamccawley/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
```
This previous PR added `net-http` as a dev dependancy to try fix this. https://github.com/cipherstash/activestash/pull/33. And was released as part of version 0.4.1.
When testing i'm still seeing these …
> Update net-http to be a runtime dep

- lib/active_stash/query_builder.rb
- spec/query_spec.rb
We want to support regex matching, but we're not quite there yet.
> Provide helpful error message when regexp passed to =~

- lib/tasks/active_stash.rake
Some models don't react well to being loaded more than once, but ActiveRecord does a very poor job of avoiding duplicate loading.
So we've got to slum it somewhat and trip the dependency loader to make sure they're only getting loaded once.
> Load models correctly

- lib/tasks/active_stash.rake
Gives us a little more flexibility in where we send them next.
> Direct users signing up through the website

- CHANGELOG.md
- README.md
The readme has an example of using count in the query.
This is not currently supported in ActiveStash.
Remove usage of count in example.
> Update readme to remove usage of count from query example

- .github/workflows/build.yml
- activestash.gemspec
- gemfiles/ruby_client_main.gemfile
This PR adds a job to CI that runs specs against the current `main` HEAD of ruby-client.
This should help catch changes in ruby-client that break ActiveStash before problem changes are released.
> Add CI job for running specs against main branch of Ruby client

- .github/workflows/build.yml
* Fix bug where ruby 3.1 tests would run twice instead of using both 3.0 and 3.1
* Don't bother making PG database names unique since each job gets a fresh DB and long names get truncated
* Don't bother clearing the the PG DB since each job gets a fresh DB
> Clean up CI workflow for tests

- README.md
- activestash.gemspec
- lib/active_stash/schema_builder.rb
- lib/active_stash/stash_indexes.rb
- spec/active_stash/unique_indexes_spec.rb
- spec/put_spec.rb
- spec/support/user_invalid_unique_indexes.rb
- spec/support/user_unique_indexes.rb
This PR updates:
- stash indexes and the schema builder to handle the ability specify a unique constraint on range and exact indexes.
- Raises an error if a unique constraint is specified on a match index.
- Tests to cover the above and check if an error is raised when a duplicate record is inserted.
- I also added a test to check to see if case sensitivity made a difference. A RecordPutFailure will still be raised even if the field is in a different case.
- Updates readme.
> Add ability to specify a unique constraint on exact and range indexes

- .gitignore
- README.md
- Rakefile
When running `rake release` the imported bundler gem release task is called instead of the git release task in the rakefile.
This is because we import `require "bundler/gem_tasks"` in the rake file. We do currently use a task from this import, `bundle exec rake install` to install a local version of the gem. 
This PR updates the name of the git release task to differentiate it from the bundler gem task, and updates the reference in the readme.
> Remove bundler gem helpers to avoid conflict with git release task

- lib/active_stash/relation.rb
- spec/query_spec.rb
This change adds a basic implementation of the count method on `ActiveStash::Relation`. This is implemented by loading all records and then counting the number of results in memory.
This implementation can be replaced with a proper aggregate query once they're supported in StashRB.
> Add basic count implementation

- CHANGELOG.md
- lib/active_stash/railtie.rb
This fixes a bug where users could accidentally clobber the ActiveStash
Rake tasks.
The path used for loading Rake tasks in the Railtie used an implicit
relative path. This would cause Kernel.load to attempt to load the file
based on $LOAD_PATH. Usually this wouldn't cause any issues, but
this would load `lib/tasks/active_stash.rake` in the user's project if
they happened to have it defined. This means that the actual Rake
tasks for ActiveStash would never be loaded an instead would be
clobbered by the user's `active_stash.rake` file.
Using an absolute path ensures that users can't accidentally clobber
the Rake tasks provided by ActiveStash.
See: https://ruby-doc.org/core-3.1.2/Kernel.html#method-i-load
> Fix path to Rake tasks in Railtie

- README.md
When running this query example
```ruby
User.query.order(email: :desc, :created_at)
```
A syntax error is returned
```ruby
(irb):7: syntax error, unexpected ')', expecting => (SyntaxError)
...rder(email: :desc, :created_at)
```
This PR updates the query example to the correct format.
> Update query example in readme tutorial

- lib/active_stash/stash_indexes.rb
- spec/active_stash/active_record_encryption_spec.rb
- spec/active_stash/stash_indexes_spec.rb
- spec/active_stash/unique_indexes_spec.rb
- spec/spec_helper.rb
- spec/support/migrations/create_users4.rb
- spec/support/user4.rb
This PR fixes an issue where incorrect indexes are being created for anything other than a string type.
This is due to active record setting the type for all encrypted attributes to text.
More info here https://cipherstash.slack.com/archives/C01G7UGNQ3U/p1661470867621559
I have tested out Lockbox, and this doesn't have the same issue. The setup includes a step where you specify the type on the encrypted field in the model. In ActiveStash, it comes through as an ActiveModel type, with the actual type.
```
Key:
"age"
Value:
#<ActiveModel::Type::Integer:0x0000000146749ae0 @precision=nil, @scale=nil, @limit=8, @range=-9223372036854775808...9223372036854775808>
```
> check if attribute is encrypted before checking type and add test

- lib/tasks/active_stash.rake
Adds a check for workspace id when running login.
Returns error if one isn't provided, and provides an example of how to provide it.
> Check for workspace arg when logging in

- CHANGELOG.md
- lib/tasks/active_stash.rake
Adds rescue's to handle failures gracefully when load or create profile errors are returned.
Before
After
> Rescue errors on login

- lib/active_stash/assess.rb
- lib/active_stash/assess/column_name_rules.rb
- lib/active_stash/error.rb
- lib/active_stash/matchers.rb
- lib/tasks/active_stash.rake
This PR updates the `ecrypt_sensitive_fields` RSpec matcher to raise an error (and fail the test) when the assessment file is outdated.
This works by:
1. Recording all fields currently on each model when the report is generated
2. Checking that the current fields on the model being tested match the fields recorded in the assessment file
Here's an example of the error message for an outdated assessment file:
And here's an example of the new format for the assessment file to support this:
```yml
---
User:
- :field: id
:sensitive: false
- :field: name
:sensitive: true
:comment: 'suspected to contain: names'
- :field: email
:sensitive: true
:comment: 'suspected to contain: emails'
- :field: password_digest
:sensitive: false
- :field: gender
:sensitive: true
:comment: 'suspected to contain: …
```
> Raise error in RSpec matcher when assessment is outdated

- lib/active_stash/assess/column_name_rules.rb
- lib/active_stash/matchers.rb
- spec/active_stash/assess/column_name_rules_spec.rb
When running the RSpec matcher against a model that doesn't have any encrypted fields added yet, the below response is returned on the test.
```
Pending: (Failures listed here are expected and do not affect your suite's status)
1) User encrypts sensitive fields
Failure/Error: expect(described_class).to encrypt_sensitive_fields
NoMethodError:
undefined method `include?' for nil:NilClass
```
This is because we are not checking for nil being returned if there are no encrypted attributes added yet.
This PR adds in a check that the encrypted attributes is an array, before checking the field name is included.
I'm also squeezing in, adding in `suburb` as a potential address field, as need this for the example in the getting started guide
> Assess: Check encrypted attributes is an array

- lib/active_stash/matchers.rb
The data type of encrypted attributes is a Set not an Array.
Fixes the check on encrypted attributes to check for a Set type, not an array.
> Assess: check if encrypted attribute is a set not an array

- README.md
- lib/active_stash/search.rb
This PR adds some minor fixes in the README and docs.
* Consistently use `rake` command for running ActiveStash tasks
* Consistenly use `$` at the start of command line code examples
* Add step for creating collections to "Getting started" section
* Correct `active_stash:create` to be `active_stash:collections:create`
* Correct `active_stash:collections:create[User]` to not use an arg (because this command doesn't accept any args)
> Make minor README and doc fixes

- lib/tasks/active_stash.rake
- spec/tasks/collections/describe_spec.rb
This PR fixes a `NoMethodError` while running `rake active_stash:collections:describe`.
The error before was:
```
NoMethodError: undefined method all for #ActiveStash::IndexLookup:0x000000013087cec8
```
`all` is no longer a method on `stash_indexes` (likely from the change in https://github.com/cipherstash/activestash/pull/79). We can use `stash_indexes.indexes` instead.
> Fix describe collection task error

- README.md
- activestash.gemspec
- lib/active_stash/assess.rb
- lib/active_stash/matchers.rb
- lib/tasks/active_stash.rake
- spec/active_stash/assess_spec.rb
- spec/spec_helper.rb
- spec/support/assess_user_active_record_encryption.rb
- spec/support/assess_user_lockbox.rb
- spec/support/assess_user_no_encryption.rb
- spec/support/migrations/create_assess_tables.rb
- spec/support/user3.rb
This PR adds Lockbox support to the `encrypt_sensitive_fields` matcher and adds specs for Assess (both the task and matcher).
Note that columns that follow the Lockbox convention of using a `_ciphertext` suffix will still not show up as sensitive in the assessment. However, columns that use non-default names (e.g. don't use the suffix) and get picked up as sensitive will be properly marked as encrypted.
I've also fixed a typo in the `User3` model that could cause test flake.
> Add Lockbox support to encrypt_sensitive_fields matcher

- activestash.gemspec
- lib/tasks/active_stash.rake
This PR fixes a bug where users were not able to log in using existing profiles via `rake active_stash:login`.
Related ruby-client PR: https://github.com/cipherstash/ruby-client/pull/23.
Note: this PR does not change the behaviour that existing profiles can be clobbered when running `rake active_stash:login` with the workspace arg.
> Update login rake task to use CipherStash::Client.login

- activestash.gemspec
- lib/active_stash/schema_builder.rb
Bumps cipherstash-client version to v0.18.0 which includes update to ngram tokenization.
Updates ngram tokenization settings to use min and max length.
> Update ngram tokenization setting
